### ISSUE TITLE
Improve logging during copy operation to in case of failure

### ISSUE THREAD

**Issue by gmcculloug** [ManageIQ/manageiq-automation_engine#107]
Followup work from https://bugzilla.redhat.com/show_bug.cgi?id=1461427

cc @d-m-u

**Comment by JPrause** [comment]
@d-m-u with your reference to the PR above, does that mean this issue can be closed?
If yes, can you please close this issue, if not, can you remove the stale label

**Comment by d-m-u** [comment]
Sure, can be closed, I would've, if I could close it. I have no power to do anything here.

**Comment by JPrause** [comment]
Thanks @d-m-u 
@miq-bot close_issue
