### ISSUE TITLE
introduce internal automate method

### ISSUE THREAD

**Issue by bzwei** [ManageIQ/manageiq-automation_engine#135]
Currently every method in automate is configured to run in Drb and considered a user provided script. However manageiq is shipped with many automate methods which are not really user provided. We should introduce internal automate methods that run default implementations internally but allow users to override with an external script.

**Comment by bzwei** [comment]
@miq-bot assign @mkanoor 
@mkanoor please provide more details.

cc @gmcculloug @tinaafitz

**Comment by gmcculloug** [comment]
Closing based on comment in related PR https://github.com/ManageIQ/manageiq-automation_engine/pull/136#issuecomment-356740181
