### ISSUE TITLE
Expose cloud_volume to automate

### ISSUE THREAD

**Issue by idood** [ManageIQ/manageiq-automation_engine#143]
Looking to expose aws cloud_volume methods to automate 
create/delete/attach volume and create/delete snapshot

miq_ae_service_manageiq-providers-cloud_manager-vm.rb
     add expose :cloud_volumes, :association => true

miq_ae_service_cloud_volume.rb
   add expose :create_volume_snapshot, :override_return => nil

**Comment by JPrause** [comment]
@idood is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
