### ISSUE TITLE
vm_reconfigure_request error checking quota's

### ISSUE THREAD

**Issue by Stromweld** [ManageIQ/manageiq-automation_engine#150]
A user with only a tenant quota for memory set to 256GB is trying to reconfigure a VM and add an additional HDD to his machine. We are seeing an error in the quota used method when calling check_quota. When the quota is turned off then he is able to provision the drive without error.

We are running MIQ Fine-4 and VMware vcenter 6.5.
Gist contains the logs for the vm_reconfigure_request.
https://gist.github.com/Stromweld/d59742714eda7e732378e262217dd412

**Comment by gmcculloug** [comment]
@tinaafitz @billfitzgerald0120 Please review

**Comment by gmcculloug** [comment]
@billfitzgerald0120 Do you know if this has been resolved?

**Comment by billfitzgerald0120** [comment]
@gmcculloug This is still an issue.  When Memory is over quota, the reconfigure request will be denied even if there is no request for more memory.  I tried to add just a drive when memory was exceeded and it was denied.

**Comment by gmcculloug** [comment]
Thanks for looking into that @billfitzgerald0120.  I'll pin the issue for now.

**Comment by billfitzgerald0120** [comment]
@gmcculloug I think its a one line change but I want to discuss with Tina in case I'm missing something
