### ISSUE TITLE
[RFE] Allow max_retries override at instance level

### ISSUE THREAD

**Issue by fdupont-redhat** [ManageIQ/manageiq-automation_engine#163]
When one creates a state machine, the maximum number of retries for a state is set at the class level. However, a use case of state machines is to create generic state machines where the state name is 'StateX' and URI is specified only at the instance level, not the class. In this case, to stay generic, one is tempted to set the maximum number of retries to a very high number for each state, to cover whatever situation at the instance level.

Allowing to override the maximum number of retries at the instance level would help creating generic state machine classes (scaffolds) with no maximum retries set, and then let the instance specify the maximum retries based on the actual URI.

**Comment by fdupont-redhat** [comment]
@mkanoor @tinaafitz What do you think about this ? The idea comes from my implementation on V2V state machines, where the state machine class is just a scaffold. So, I had to set a max_retries for all states as I don't know in advance what it will be used for.

**Comment by mkanoor** [comment]
@fdupont-redhat @tinaafitz @gmcculloug 
The max_retries can be set at the instance level, the UI currently doesn't support it, we can expose it in the UI.

**Comment by fdupont-redhat** [comment]
Awesome, I didn't expect less from you :+1: 
Sould I open an RFE in manageiq-ui-classic repo ?

**Comment by mkanoor** [comment]
Yes, lets open an issue in the UI repo, the MiqAeValue table allows for setting of the max_retries. If they can make these fields show up only for state machines it would be good. e.g. on_entry/on_exit/on_error/max_retries/max_time should only be visible if the field is a state. For relationships and attributes it doesn't make sense.

The Automate Engine might work I am not sure but once the MiqAeValue has the max_retries/max_time we can fix the engine if it doesn't take care of it already.

**Comment by fdupont-redhat** [comment]
@mkanoor RFE opened: ManageIQ/manageiq-ui-classic/issues/3560.
Do you know who could look at it ?

**Comment by gmcculloug** [comment]
I added an assignee to the ui-classic issue.

**Comment by tinaafitz** [comment]
I manually changed a state machine instance max_retries value and verified the instance value is used in resolution.

**Comment by gmcculloug** [comment]
@fdupont-redhat With PR https://github.com/ManageIQ/manageiq-ui-classic/pull/3562 merged can this issue and https://github.com/ManageIQ/manageiq-ui-classic/issues/3560 be closed now?

**Comment by fdupont-redhat** [comment]
@gmcculloug Yes, we can.
