### ISSUE TITLE
MiqAeNamespace should use ancestry instead of acts_as_tree

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-automation_engine#409]
MiqAeNamespace is requested to walk its tree fairly frequently, but since it uses acts_as_tree, it effectively emits 1 query per level of the tree.  One common path for this is asking an object's fqname.  If MiqAeNamespace used ancestry, then it would be one query to get the fqname.

cc @tinaafitz 

---

- [ ] [Schema PR](https://github.com/ManageIQ/manageiq-schema/pull/455)
- [ ] [Core PR](https://github.com/ManageIQ/manageiq/pull/19824)
- [ ] [Automate Engine PR](https://github.com/ManageIQ/manageiq-automation_engine/pull/425)
- [ ] [UI PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/6668)

**Comment by kbrock** [comment]
UI PR no longer needed.

**Comment by NickLaMuro** [comment]
I didn't do it!  I swear!  I'm innocent I say!  INNOCENT!!!

**Comment by kbrock** [comment]
The comment was "Fixes ManageIQ/manageiq-automation_engine#409"
so the github will close the one fixed and claim the merger did it.
