### ISSUE TITLE
Add specs for classes using EmsOperationsMixin based on queue_name change

### ISSUE THREAD

**Issue by gmcculloug** [ManageIQ/manageiq-automation_engine#426]
See https://github.com/ManageIQ/manageiq-automation_engine/pull/419#issuecomment-584287073

The following classes are affected by the queue_name change but do not have proper test coverage:

- ems_cluster.rb
- ems_folder.rb
- host.rb
- manageiq-providers-cloud_manager.rb
- manageiq-providers-network_manager.rb
- manageiq-providers-vmware-infra_manager-host_esx.rb
- vm_or_template.rb

**Comment by d-m-u** [comment]
@miq-bot assign @d-m-u

**Comment by d-m-u** [comment]
Closing because this was addressed in the linked https://github.com/ManageIQ/manageiq-automation_engine/pull/427 or rather I would close if I had the power but apparently only the powers that be do. Juuuuuust kidding.
