### ISSUE TITLE
Unable to Pass A List As Extra Variable For Ansible Playbooks

### ISSUE THREAD

**Issue by dmetzger57** [ManageIQ/manageiq-automation_engine#435]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1659092

When passing a list as an extra variable to an ansible playbook, the list is always treated as a string. Should be able to insert a list into an ansible playbook as an extra variable.

**Comment by NickLaMuro** [comment]
Just taking a quick look at this as it was just assigned to me:

Initial thoughts is that we would have to see how `ansible-runner` would allows passing of arrays as a command line arg, which I don't know off hand.  My guess is that it would/should be possible to use the existing UI to pass array based arguments without the need to make changes to the UI, or even the backend (possibly).

* * *

As a workaround, my guess is it should also be possible to re-structure most playbooks where this feature wouldn't be necessary, but that is hard to know without concrete examples of where this might be used.  An example of this in an unrelated subject matter is how the `NFS_EXPORT_*` vars in https://github.com/ehough/docker-nfs-server is handled for this docker image, where you can created vars `NFS_EXPORT_1`, NFS_EXPORT_2`, etc. as a way of defining "array like data" or list based data, but without actually needing a defined `N` to do so.

Not a perfect solution, but might avoid adding unneeded complexity to our product that we have to support that can be solved in a different way outside of it.
