### ISSUE TITLE
Bug with handling of Arrays in Automate

### ISSUE THREAD

**Issue by zigaSRC** [ManageIQ/manageiq-automation_engine#480]
There's an issue when passing **arrays of strings with commas** between automate methods (indcluding output from multiselect dialog).

### Current Behavior:
Saving `["test1,test2", "test3,test4"]` (_**2 elements**_) under $evm (or selecting multiple strings with commas in a dialog) and then reading the value in another/different automate method returns `["\"test1", "test2\"", "\"test3", "test4\""]` (_**4 elements**_)

### Expected Behavior:
Saving an array of strings in one method should produce the exact same array when reading the value in another method. 

### Steps To Reproduce:

1. Create two automate methods that are run one after another.
2. Save the above array under $evm in the first method.
`$evm.root['test'] = ["test1,test2", "test3,test4"]`
3. Read the value in the second method.
`$evm.log('info', "Array: #{$evm.root['test']}")`
4. See a different array returned than was saved.

### Environment:
ManageIQ Lasker-1

### Anything else:
I suspect the split method here:
https://github.com/ManageIQ/manageiq-automation_engine/blob/5be34d7779dbd7e968326076c39aacca197fc59f/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb#L491
splits the string (array) on **every** comma even if they are a part of a string and not a delimiter between elements.

Using eval() would solve this problem, such as many others (nested arrays or other comma issues). Though I must admit I don't know how the values are handled on the other end to judge if this would be a safe use of the eval method.

**Comment by Fryguy** [comment]
cc @akhilkr128
