### ISSUE TITLE
Multiselect value is stored in a different format.

### ISSUE THREAD

**Issue by kTipSSIoYv** [ManageIQ/manageiq-automation_engine#501]
In Morphy release, multiselect array is storing data as ["118\u001F119"] instead of ["118", "119"]. I'm unable to retrieve data by index. 

Any workaround to fix this?

![image](https://user-images.githubusercontent.com/9666915/177589274-59d51076-1706-431f-9e9a-258de106fb86.png)

**Comment by jeffibm** [comment]
Hey @kTipSSIoYv , I am not able to identify the page from which this issue is reported. Could you please post a full page screenshot with breadcrumbs?

**Comment by kTipSSIoYv** [comment]
Create a service dialog.  Choose any multiselect and it'll display the value in a weird format in the request section.


![image](https://user-images.githubusercontent.com/9666915/177713665-4527b209-5e1f-4b6f-9d1c-b34f2a88671b.png)

![image](https://user-images.githubusercontent.com/9666915/177713734-e82fd63a-64b9-46aa-b122-1c1e6339f028.png)

Create a method to retrieve the dialog first value. (get_option or get_option_array)

![image](https://user-images.githubusercontent.com/9666915/177714309-15a4ffea-9a49-42b9-ab4c-a24af2fb5b02.png)

You'll see that the output retrieves both value with a special character in between. 

```
[----] I, [2022-07-06T09:05:14.492607 ManageIQ/manageiq#314:2aad21d5b6fc]  INFO -- automation: Q-task_id([r745_miq_provision_1962]) <AEMethod launch_ansible_job> job_template_by_id is 118▼119
```

**Comment by akhilkr128** [comment]
Looking into the issue.

**Comment by Fryguy** [comment]
> Is there any workaround I can try? I'm kind of stuck due to this issue.

@kTipSSIoYv Yes, in your automate code you can do: 

```diff
- job_template_array = prov.get_option_array(:job_template_id)
+ job_template_array = prov.get_option_array(:job_template_id).split("\x1F")
  job_template_array = job_template_array[0]
```

**Comment by akhilkr128** [comment]
I have created the service dialogue on Morphy branch with multi-select dropdowns and added a dynamic dropdown also which is working fine. Can you tell me more information about populating this data on dropdown? So that I can reproduce this.
<img width="639" alt="Screenshot 2022-07-12 at 4 52 43 PM" src="https://user-images.githubusercontent.com/16753936/178478858-ccda7018-d42d-42a1-a155-7e1f154b6b4c.png">

**Comment by kTipSSIoYv** [comment]
It seems like its working only for you.

I just created a new docker image using latest morphy and I still see the same issue.

![image](https://user-images.githubusercontent.com/9666915/178644852-0fbdcfe5-eabe-4c2c-a0e3-7a08387194e4.png)

**Comment by akhilkr128** [comment]
@kTipSSIoYv How you are creating this request using order button or by API?

**Comment by Fryguy** [comment]
Fixed in https://github.com/ManageIQ/manageiq-ui-classic/pull/8362
